version: '1.0'
services: 
  dl-container: 
    build: . 
    ports:
      - 8888:8888 
    volumes: 
      - .:/dl-container
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    stdin_open: true
    tty: true
    
    deploy:
     resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]